### ISSUE TITLE
ts-api-utils and tslib dependencies should be used or removed

### ISSUE THREAD

**Issue by kmturley** [jsynowiec/node-typescript-boilerplate#58]
Dependencies should be included for a reason. These are included but not used:

- https://www.npmjs.com/package/ts-api-utils
- https://www.npmjs.com/package/tslib

Either they should be used in the example `main.ts` or removed.

**Comment by jsynowiec** [comment]
This has already been discussed. 

`tslib` is a runtime library for TypeScript [importHelpers](https://www.typescriptlang.org/tsconfig/#importHelpers). When this compiler option is enabled, you need to ensure that the `tslib` module is available at runtime.

For an explanation about `ts-api-utils`, please see https://github.com/jsynowiec/node-typescript-boilerplate/issues/37 and https://github.com/jsynowiec/node-typescript-boilerplate/issues/44.

**Comment by kmturley** [comment]
Thanks for your prompt response. I understand what the libraries are, i'm questioning the need for them.

https://www.npmjs.com/package/tslib and importHelpers configuration reduces code size when compiling to `es2015`, but your project uses `es2022`.

For example:
```
git clone https://github.com/jsynowiec/node-typescript-boilerplate.git
cd node-typescript-boilerplate
npm install
npm run build
cat ./build/src/main.js
```

Then update `tsconfig.json` value`"importHelpers": false` and then:
```
npm run build
cat ./build/src/main.js
```

Notice nothing has changed in the built main.js file.

Then update `tsconfig.json` value`ES2015` and then:
```
npm run build
cat ./build/src/main.js
```

Notice the bloat code is there for es2015, so tslib is useful for es2015.

I didn't try every helper method in: https://github.com/microsoft/tslib/blob/main/modules/index.js
but my assumption is many of these are not needed when compiling to es2022

**Comment by jsynowiec** [comment]
I appreciate your comment. Because this project has been around for 8 years now, and went through many updates and switched over several Node and TypeScript LTS versions and ES targets, this indeed may be an obsolete artifact now. I will take a look at some point if it is fine to remove, and it does not break anything.

However, I am still convinced that `ts-api-utils` needs to stay pinned. It is used by, for example, `eslint`. In the past, there were at least a few non-obvious problems related to version incompatibilities with the old `tsutils`, what `ts-api-util` replaces, and the linter and its dependencies.
